### ISSUE TITLE
Consider esprima as a longer term replacement for typhonjs-escomplex

### ISSUE THREAD

**Issue by sgb-io** [sgb-io/codehawk-cli#101]
https://github.com/jquery/esprima

**Comment by 1000i100** [comment]
It sure look like a good replacement !

**Comment by sgb-io** [comment]
This might still work well, but the signs at the moment for the esprima project aren't so good: the primary maintainers appear to be inactive on the project. But, it may still be good enough, and is a relatively mature project. Usage of newer syntax and language features could eventually become an issue.

It's also worth looking at the parser components of Rollup (js), Esbuild (golang), SWC (rust) and Turbo (rust). This would probably represent a major new version.

**Comment by sgb-io** [comment]
Closing due to https://github.com/sgb-io/codehawk-cli/issues/122

SWC was the answer - that is what FTA is based on. Check it out!
