### ISSUE TITLE
[bug?] Times Used/Depended On

### ISSUE THREAD

**Issue by 1000i100** [sgb-io/codehawk-cli#113]
` Times Used/Depended On` Always display `1` in my project, but some of my files are import more than one time. Do you only look for `require` ?

**Comment by sgb-io** [comment]
@1000i100 codehawk-cli doesn't detect dependencies directly (this is carried out by `typhonjs-escomplex`), but it does do some file/patch matching to add the numbers up.

If you have an example, I'd be happy to look at this. Also, please include what OS you are using.

**Comment by 1000i100** [comment]
Here is the project i've tried it again :
https://git.duniter.org/libs/g1lib.js
I'm on Linux, TuxedoOS based on Ubuntu 20.04 I will do the 22.04 update soon).
I'm using node v16.4.1 or node v19.2.0 if i need v18+ features.

**Comment by sgb-io** [comment]
Verification is needed, but at a glance, I don't think codehawk-cli currently supports `.mjs`, which would explain the problem. Shouldn't be too hard to fix.

**Comment by sgb-io** [comment]
Closing due to https://github.com/sgb-io/codehawk-cli/issues/122

FTA doesn't currently support "times depended on" currently, but if this is something you are interested in, please file an issue in the FTA repo. Thanks!
