### ISSUE TITLE
maintainability badge

### ISSUE THREAD

**Issue by 1000i100** [sgb-io/codehawk-cli#39]
With global maintainability #38 come the badge communication oportunity !

put a maintainability badge on my README.md to show how well maintaned is my project !

**Comment by 1000i100** [comment]
On this project : https://framagit.org/g1/g1lib.js/
I've added maintainability badge, threshold (#40) based on es6-plato.
I think most of my work could be reuse here in codehawk-cli.

https://framagit.org/g1/g1lib.js/-/blob/main/CI/plato-badges.js
https://framagit.org/g1/g1lib.js/-/blob/main/package.json#L29

**Comment by sgb-io** [comment]
Support now exists in #49.

Will add the badge to this project itself when the feature is published in a new version.

**Comment by sgb-io** [comment]
cc @1000i100 this works now! you can see the 2 badges on the README now.

I will leave this open for now as it needs some better docs.

**Comment by 1000i100** [comment]
cool !! :D

**Comment by sgb-io** [comment]
This is now available on npm with `codehawk-cli` @ ~7.1.2~ 7.1.4! Also added a note to the docs about it. Will also update the [example project](https://github.com/sgb-io/codehawk-cli-example) to show users how to use it.
