### ISSUE TITLE
maintainability threshold

### ISSUE THREAD

**Issue by 1000i100** [sgb-io/codehawk-cli#40]
What's the worst maintainabilty i can allow for CI to pass ?
With 2 thresholds :
- worst file maintainability threshold
- average maintainability threshold

**Comment by sgb-io** [comment]
@1000i100 The numbers can be highly subjective, however, my anecdotal findings (based on working with it for 18-24 months and trialing the tool against some commercial projects) are approximately this:

75+: minimal complexity, highly likely to be highly maintainable code or a small volume of code
65+: slight complexity, likely to be highly maintainable code
50-65: some complexity, likely to be improvable in most circumstances
0-50: lots of complexity or volume, file either needs improvement or splitting apart

These thresholds seem to work well as a general "you should look here" guide.

There is currently some generic output (Needs Improvement/Could Be Better/OK) in the cli output (based on similar arbitrary numbers).

My current thinking is that there is sensible defaults, but users could configure this.

Features needed

- Allow users to specify a required threshold, single worst case and overall average
- (cli) Exist code 1 if either rule is violated

**Comment by sgb-io** [comment]
This feature should now be viable after the changes in #49

**Comment by sgb-io** [comment]
@1000i100 Hi, this feature is now available with ~7.1.2~ 7.1.4! 🚀

**Comment by 1000i100** [comment]
Thank you ! :D
